"""create jobs table

Revision ID: 42c705011431
Revises: 8824dddcfb80
Create Date: 2025-10-27 20:23:47.835331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42c705011431'
down_revision: Union[str, Sequence[str], None] = '8824dddcfb80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_display', sa.String(), nullable=False),
    sa.Column('title_display', sa.String(), nullable=False),
    sa.Column('location_display', sa.String(), nullable=True),
    sa.Column('source_display', sa.String(), nullable=True),
    sa.Column('company_key', sa.String(), nullable=False),
    sa.Column('title_key', sa.String(), nullable=False),
    sa.Column('location_key', sa.String(), nullable=True),
    sa.Column('source_key', sa.String(), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('referred', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cv', sa.Text(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('application_url', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('Applied','Home_Assignment','Interview','Offer','Offer_Accepted','Rejected')", name='chk_status'),
    sa.CheckConstraint('char_length(trim(company_display)) > 0', name='chk_company_not_empty'),
    sa.CheckConstraint('char_length(trim(title_display)) > 0', name='chk_title_not_empty'),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('company_key', 'title_key', 'date_applied', 'source_key', name='uq_jobs_key_date_source')
    )
    op.create_index('idx_jobs_company_key', 'jobs', ['company_key'], unique=False)
    op.create_index('idx_jobs_date_applied', 'jobs', ['date_applied'], unique=False)
    op.create_index('idx_jobs_location_key', 'jobs', ['location_key'], unique=False)
    op.create_index('idx_jobs_source_key', 'jobs', ['source_key'], unique=False)
    op.create_index('idx_jobs_status', 'jobs', ['status'], unique=False)
    op.create_index('idx_jobs_title_key', 'jobs', ['title_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_jobs_title_key', table_name='jobs')
    op.drop_index('idx_jobs_status', table_name='jobs')
    op.drop_index('idx_jobs_source_key', table_name='jobs')
    op.drop_index('idx_jobs_location_key', table_name='jobs')
    op.drop_index('idx_jobs_date_applied', table_name='jobs')
    op.drop_index('idx_jobs_company_key', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
