"""Add User model, Job.public_id UUID, per-user unique constraint, indexes

Revision ID: 9ab7a54291be
Revises: df8ab7e8d9a9
Create Date: 2025-11-06 12:13:31.948486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab7a54291be'
down_revision: Union[str, Sequence[str], None] = 'df8ab7e8d9a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
