"""Add User model, Job.public_id UUID, per-user unique constraint, indexes

Revision ID: df8ab7e8d9a9
Revises: 42c705011431
Create Date: 2025-11-06 12:06:41.375668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df8ab7e8d9a9'
down_revision: Union[str, Sequence[str], None] = '42c705011431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.add_column('jobs', sa.Column('public_id', sa.UUID(), nullable=False))
    op.add_column('jobs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('uq_jobs_key_date_source', 'jobs', type_='unique')
    op.create_index('idx_jobs_user_id', 'jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_jobs_public_id'), 'jobs', ['public_id'], unique=True)
    op.create_unique_constraint('uq_jobs_user_key_date_source', 'jobs', ['user_id', 'company_key', 'title_key', 'date_applied', 'source_key'])
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint('uq_jobs_user_key_date_source', 'jobs', type_='unique')
    op.drop_index(op.f('ix_jobs_public_id'), table_name='jobs')
    op.drop_index('idx_jobs_user_id', table_name='jobs')
    op.create_unique_constraint('uq_jobs_key_date_source', 'jobs', ['company_key', 'title_key', 'date_applied', 'source_key'])
    op.drop_column('jobs', 'user_id')
    op.drop_column('jobs', 'public_id')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
